# Generated by Django 3.1.5 on 2021-04-27 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='soundfileuser',
            name='activation_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
