# Generated by Django 3.1.5 on 2021-05-04 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_soundfileuser_activation_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='soundfileuser',
            name='membership',
            field=models.IntegerField(default=0),
        ),
    ]
