# Generated by Django 3.1.5 on 2021-03-30 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userfeatures', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='playlist',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='playlist_user'),
        ),
    ]
