# Generated by Django 3.1.5 on 2021-03-31 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userfeatures', '0002_auto_20210330_2310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eisodelike',
            old_name='Episode',
            new_name='episode',
        ),
        migrations.AlterField(
            model_name='eisodelike',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='episode_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
