# Generated by Django 3.1.5 on 2021-04-01 01:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('podcasts', '0001_initial'),
        ('userfeatures', '0003_auto_20210331_2024'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EisodeLike',
            new_name='EpisodeLike',
        ),
    ]
