# Generated by Django 3.1.5 on 2021-04-12 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userfeatures', '0005_episodesavepoint'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='episodesavepoint',
            constraint=models.UniqueConstraint(fields=('episode', 'user'), name='save_point_episode'),
        ),
    ]
