# Generated by Django 3.1.5 on 2021-04-15 02:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userfeatures', '0006_auto_20210412_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodesavepoint',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
