# Generated by Django 3.1.5 on 2021-04-16 00:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userfeatures', '0007_episodesavepoint_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='EpisodeCommentReplyNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen', models.BooleanField(default=False)),
                ('ParentEpisodeComment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userfeatures.episodecomment')),
                ('user_notified', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episode_comment_reply_notifications', to=settings.AUTH_USER_MODEL)),
                ('user_notifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EpisodeCommentLikeNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen', models.BooleanField(default=False)),
                ('episodeComment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userfeatures.episodecomment')),
                ('user_notified', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episode_comment_like_notifications', to=settings.AUTH_USER_MODEL)),
                ('user_notifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
