# Generated by Django 3.1.5 on 2021-04-16 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userfeatures', '0008_episodecommentlikenotification_episodecommentreplynotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='EpisodeCommentNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen', models.BooleanField(default=False)),
                ('notify_type', models.CharField(max_length=40)),
                ('ParentEpisodeComment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userfeatures.episodecomment')),
                ('user_notified', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episode_comment_reply_notifications', to=settings.AUTH_USER_MODEL)),
                ('user_notifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='episodecommentreplynotification',
            name='ParentEpisodeComment',
        ),
        migrations.RemoveField(
            model_name='episodecommentreplynotification',
            name='user_notified',
        ),
        migrations.RemoveField(
            model_name='episodecommentreplynotification',
            name='user_notifier',
        ),
        migrations.DeleteModel(
            name='EpisodeCommentLikeNotification',
        ),
        migrations.DeleteModel(
            name='EpisodeCommentReplyNotification',
        ),
    ]
