# Generated by Django 3.1.5 on 2021-04-16 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userfeatures', '0009_auto_20210416_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episodecommentnotification',
            name='user_notifier',
        ),
    ]
