# Generated by Django 3.1.5 on 2021-04-16 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userfeatures', '0010_remove_episodecommentnotification_user_notifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodecommentnotification',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
