# Generated by Django 3.1.5 on 2021-04-16 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userfeatures', '0011_episodecommentnotification_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episodecommentnotification',
            old_name='ParentEpisodeComment',
            new_name='episodeComment',
        ),
    ]
