# Generated by Django 3.1.5 on 2021-04-16 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userfeatures', '0012_auto_20210416_1804'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episodecommentnotification',
            options={'ordering': ['-update_time']},
        ),
        migrations.AddField(
            model_name='episodecommentnotification',
            name='update_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
