# Generated by Django 3.1.5 on 2021-04-18 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userfeatures', '0013_auto_20210416_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodecommentnotification',
            name='Playlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userfeatures.playlist'),
        ),
        migrations.AlterField(
            model_name='episodecommentnotification',
            name='episodeComment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userfeatures.episodecomment'),
        ),
    ]
