# Generated by Django 3.1.5 on 2021-04-18 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userfeatures', '0014_auto_20210418_1803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episodecommentnotification',
            old_name='Playlist',
            new_name='playlist',
        ),
    ]
