# Generated by Django 3.1.5 on 2021-04-19 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userfeatures', '0018_episodecommentnotification_user_giver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episodecommentnotification',
            name='user_giver',
        ),
    ]
