# Generated by Django 3.1.5 on 2021-04-21 20:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userfeatures', '0023_auto_20210420_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='update_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
