# Generated by Django 3.1.5 on 2021-04-09 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userfeatures', '0004_auto_20210401_0144'),
        ('podcasts', '0011_auto_20210408_0733'),
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flag',
            name='episodeComment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userfeatures.episodecomment'),
        ),
        migrations.AddField(
            model_name='flag',
            name='podcast',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='podcasts.podcast'),
        ),
        migrations.AddField(
            model_name='flag',
            name='reason',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flag',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.soundfileuser'),
            preserve_default=False,
        ),
    ]
