# Generated by Django 3.1.5 on 2021-04-10 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_auto_20210409_2326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flag',
            old_name='episodeComment',
            new_name='episode_comment',
        ),
    ]
