# Generated by Django 3.1.5 on 2021-04-24 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('author', models.CharField(blank=True, max_length=50, null=True)),
                ('sfPopularityScore', models.IntegerField(default=0)),
                ('indexPopularityScore', models.IntegerField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, max_length=300, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('rss_feed', models.TextField(unique=True)),
                ('etag', models.CharField(default='N/A', max_length=254)),
                ('last_modified', models.CharField(default='N/A', max_length=254)),
                ('update_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('inReview', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PodcastCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='podcast_links', to='podcasts.category')),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_links', to='podcasts.podcast')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('media_url', models.URLField()),
                ('guid', models.CharField(max_length=254, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('pub_date', models.DateField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now_add=True, null=True)),
                ('duration', models.IntegerField(default=0)),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podcasts.podcast')),
            ],
        ),
        migrations.AddConstraint(
            model_name='episode',
            constraint=models.UniqueConstraint(fields=('podcast', 'guid'), name='podcast_guid'),
        ),
    ]
