# Generated by Django 3.1.5 on 2021-04-02 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='author',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='podcast',
            name='indexPopularityScore',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
