# Generated by Django 3.1.5 on 2021-04-02 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0002_auto_20210402_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='podcast',
            name='inReview',
            field=models.BooleanField(default=False),
        ),
    ]
