# Generated by Django 3.1.5 on 2021-04-25 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0003_auto_20210425_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
