# Generated by Django 3.1.5 on 2021-04-02 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0003_auto_20210402_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='etag',
            field=models.CharField(default='N/A', max_length=254),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='last_modified',
            field=models.CharField(default='N/A', max_length=254),
        ),
    ]
