# Generated by Django 3.1.5 on 2021-04-03 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0004_auto_20210402_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='media_url',
            field=models.URLField(),
        ),
    ]
