# Generated by Django 3.1.5 on 2021-04-25 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0004_auto_20210425_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='guid',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
