# Generated by Django 3.1.5 on 2021-04-25 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0006_auto_20210425_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='indexPopularityScore',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
