# Generated by Django 3.1.5 on 2021-04-08 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0007_auto_20210407_0442'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='category',
            name='podcasts',
            field=models.ManyToManyField(blank=True, to='podcasts.Podcast'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='categories',
            field=models.ManyToManyField(blank=True, to='podcasts.Category'),
        ),
    ]
