# Generated by Django 3.1.5 on 2021-04-08 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0008_auto_20210408_0712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='podcasts',
        ),
        migrations.RemoveField(
            model_name='podcast',
            name='categories',
        ),
        migrations.CreateModel(
            name='PodcastCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='podcasts.podcast')),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='podcasts', to='podcasts.category')),
            ],
        ),
    ]
