# Generated by Django 3.1.5 on 2021-04-08 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0009_auto_20210408_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcastcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='podcasts.category'),
        ),
        migrations.AlterField(
            model_name='podcastcategory',
            name='podcast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='podcasts', to='podcasts.podcast'),
        ),
    ]
