# Generated by Django 3.1.5 on 2021-04-10 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0011_auto_20210408_0733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcast',
            name='deleted',
        ),
        migrations.AddField(
            model_name='podcast',
            name='sfPopularityScore',
            field=models.IntegerField(default=0),
        ),
    ]
