# Generated by Django 3.1.5 on 2021-04-10 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0012_auto_20210410_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
