# Generated by Django 3.1.5 on 2021-04-10 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0013_podcast_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
