# Generated by Django 3.1.5 on 2021-04-10 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0014_episode_last_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcast',
            name='duration',
        ),
        migrations.AddField(
            model_name='episode',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
