# Generated by Django 3.1.5 on 2021-04-21 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0015_auto_20210410_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
