# Generated by Django 3.1.5 on 2021-04-21 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0016_podcast_last_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='podcast',
            old_name='last_updated',
            new_name='update_time',
        ),
    ]
