# Generated by Django 3.1.5 on 2021-04-24 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0017_auto_20210421_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='image_url',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
